### PR TITLE
Remove toString method from StreamInterface #10

### PR DESCRIPTION
**Pull request by usox**
getContents will do the job if one really needs the whole data

### CODE REVIEW

**Comment by fredemmott** [comment]
I'm fine with this, though not entirely sure they're equivalent: `__toString()` is defined as returning all data, but `getContents` is defined as returning all *remaining* data. This is probably a mistake in the spec, and not widely followed though :p

Happy to merge this, but would appreciate your thoughts.

**Comment by usox** [comment]
Thats right, you have to perform a seek(0) before calling getContents (like toString does internally) to retrieve the complete content.
Another possibility: A non-magic method as replacement for toString. That would at least solve the exception problem...

**Comment by fredemmott** [comment]
How about we break compatibility a little more then, and:

- remove `__toString()`
- rename `getContents()` to `getRemainingContents()` for clarity
- add a non-magic exception-throwing `getFullContents()` that includes the seek(0)

?

**Comment by usox** [comment]
Sounds like a plan

**Pull request merged**
